Recursion's homework
ArtstiomEzepchick/HomeWorks pull request #7
Opened 2022-04-23 14:26 UTC by ArtstiomEzepchick

Please check my recursion's homework.

2022-04-23 15:06 UTC, smilejke requested changes

2022-04-23 15:06 UTC, smilejke commented on 19_04/recursion_exercises.js
> +// console.log(printList(list));
no need in `console.log` here

2022-04-23 15:06 UTC, smilejke commented on 19_04/recursion_exercises.js
> +//         console.log(printList(list.next));
no need in `console.log` here

2022-04-23 15:06 UTC, smilejke commented on 19_04/recursion_exercises.js
> +// console.log(printList(list));
no need in `console.log` here

2022-04-23 16:36 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +// function sumTo(n) {
renamed

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +//     if (n === 1) {
done

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +//     return n + sumTo(n-1);
changed

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +
changed

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +// P.S. Все запуски функций из примера выше должны работать быстро. Вызов fib(77) должен занимать не более доли секунды.
Something wrong with solutions in this article. Recursion example is the same as mine, but others don't work as expected.
I took a new variation from "learnjs" website that is much more fastest than recursion. And it has a large description to analyse what is going on.

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +// let list = {
changed

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +// console.log(printList(list));
done

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +//         console.log(printList(list.next));
done

2022-04-23 16:37 UTC, ArtstiomEzepchick commented on 19_04/recursion_exercises.js
> +// console.log(printList(list));
done

2022-04-24 09:29 UTC, smilejke approved these changes

2022-04-25 17:41 UTC, merged