added 01_05_homework (promises tasks)
ArtstiomEzepchick/HomeWorks pull request #9
Opened 2022-05-04 17:05 UTC by ArtstiomEzepchick

Smilejke, please check my 01_05_homework (promises tasks)

2022-05-04 17:41 UTC, smilejke requested changes

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +    const delayPromise = new Promise((resolve) => {
can be done in one string (return new Promise...)

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +              div.removeEventListener('transitionend', handler);
unsafe code, but we will learn it next class, so no need to change

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +// ОТВЕТ: Не эквивалентны, т.к. в первом случае, если будет ошибка - она обработается с помощью catch, а во втором случае - ошибка не будет обработана
wrong answer, see https://learn.javascript.ru/promise-basics#potrebiteli-then-catch-finally

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +async function loadNewJson(url) {
Wrong solution.
You need to use try/catch in the function and then just call it with `loadNewJson('no-such-user.json')`
Refactor it

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +    const response = await fetch(url);
the same as prev task. Try/catch here.

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +    response.status == 200 ? response.json() : new HttpError(response);
even with your wrong approach, this code is missing `return` statement

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +    response.status == 200 ? response.json() : new Error(response.status);
even with your wrong approach, this code is missing `return` statement

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +            gitHubUser = await loadJson(`https://api.github.com/users/${name}`);
`gitHubUser` is declared with `const` keyword and won't be changed

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +    while(true) {
this statement lead to infinite loop

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +async function demoGithubUser() {
wrong solution, rework

2022-05-04 17:41 UTC, smilejke commented on 01_05/promises.js
> +            err instanceof HttpError && err.response.status == 404 ?
we're not using `==`

2022-05-04 19:23 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +              div.removeEventListener('transitionend', handler);
got it

2022-05-04 19:23 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +    const delayPromise = new Promise((resolve) => {
changed

2022-05-04 19:23 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +// ОТВЕТ: Не эквивалентны, т.к. в первом случае, если будет ошибка - она обработается с помощью catch, а во втором случае - ошибка не будет обработана
corrected my answer

2022-05-04 19:27 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +            err instanceof HttpError && err.response.status == 404 ?
changed

2022-05-05 07:42 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +    while(true) {
Why infinite? I've used break-rule in try/catch construction. It doesn't help to quit cycle?

2022-05-05 07:42 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +            gitHubUser = await loadJson(`https://api.github.com/users/${name}`);
changed from "const" to "let"

2022-05-05 07:49 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +async function loadNewJson(url) {
refactored

2022-05-05 07:50 UTC, ArtstiomEzepchick commented on 01_05/promises.js
> +    const response = await fetch(url);
changed

2022-05-05 10:07 UTC, smilejke approved these changes

2022-05-05 10:07 UTC, smilejke commented on 01_05/promises.js
> +// ОТВЕТ: Не эквивалентны, т.к. в первом случае, если будет ошибка - она обработается с помощью catch, а во втором случае нету
will discuss during next class

2022-05-05 12:38 UTC, merged